policy_path: "/home/song/unitree_rl_gym/logs/rough_go2/exported/policies/policy_with_45_obs.pt"
control_dt: 0.02
kps: [20,20,20,20,20,20,20,20,20,20,20,20]
kds: [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]

default_angles: [0.1,0.8,-1.5,-0.1,0.8,-1.5,0.1,1.0,-1.5,-0.1,1,-1.5]
leg_joint2motor_idx: [3,4,5,0,1,2,9,10,11,6,7,8]
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45
action_scale: 0.25

cmd_init: [0, 0, 1]

