policy_path: "../../../../resources/policies/HIM_policy.pt"
default_angles: [0.1,0.8,-1.5,-0.1,0.8,-1.5,0.1,1.0,-1.5,-0.1,1,-1.5]
lin_vel_scale: 2.0
ang_vel_scale: 0.3
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_scale: [2.0, 2.0, 0.3]
num_actions: 12
num_obs: 270
action_scale: 0.25

